### ISSUE TITLE
OpenComputers Compatibility

### ISSUE THREAD

**Issue by yannick9906** [BlueAmulet/CCLights2#2]
I tested your Mod with OpenComputers using an adapter. It works fine unless you try to restart your OpenComputers Computer. It can't boot, because your GPU has the same name as the internal GPU provided by the GraphicsCard. It would be nice if you could simply rename the GPU Block or add "real" OpenComputers Compatibility. (See https://github.com/gamax92/CCLights2/blob/master-1.7/src/main/java/ds/mods/CCLights2/block/BlockGPU.java#L25)

**Comment by gamax92** [comment]
https://github.com/gamax92/OCLights2/
