### ISSUE TITLE
GPU API doesn't exist

### ISSUE THREAD

**Issue by Tairex777** [BlueAmulet/CCLights2#7]
I open the application "lua", type gpu.getUsedMemory() and I get
lua:1: attempt to index ? (a nil value)
When I tried "apis", it didn't appear.

**Comment by Tairex777** [comment]
Oops, wrong fork. :)

**Comment by gamax92** [comment]
The gpu block is a peripheral not an api, use `gpu=peripheral.find("GPU")`

**Comment by Tairex777** [comment]
Thanks, I didn't know how to initialize it.
